### ISSUE TITLE
[1.17.1] is there a blacklist to deny chiseling some blocks, because many modded blocks can cause crashes!!!

### ISSUE THREAD

**Issue by MSandro** [CoolMineman/BitsAndChisels#117]
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 5/12/22, 12:51 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1920.method_23752(net.minecraft.class_2338, net.minecraft.world.level.ColorResolver)" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at net.minecraft.client.color.world.BiomeColors.getColor(BiomeColors:14)
	at net.minecraft.client.color.world.BiomeColors.getFoliageColor(BiomeColors:22)
	at net.linkle.valley.ValleyClient.lambda$onInitializeClient$2(ValleyClient.java:40)
	at io.github.coolmineman.bitsandchisels.BitItemModel.lambda$static$0(BitItemModel.java:60)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:49)
	at link.infra.indium.renderer.render.ItemRenderContext.renderQuad(ItemRenderContext.java:172)
	at link.infra.indium.renderer.render.ItemRenderContext.renderFallbackWithTransform(ItemRenderContext.java:246)
	at link.infra.indium.renderer.render.ItemRenderContext.fallbackConsumer(ItemRenderContext.java:228)
	at io.github.coolmineman.bitsandchisels.BitItemModel.emitItemQuads(BitItemModel.java:90)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:112)
	at net.minecraft.client.render.item.ItemRenderer.handler$eoc000$hook_method_23179(ItemRenderer:4057)
	at net.minecraft.client.render.item.ItemRenderer.renderItem(ItemRenderer)
	at com.unascribed.fabrication.logic.WoinaDrops.interceptRender(WoinaDrops.java:145)
	at net.minecraft.client.render.entity.ItemEntityRenderer.redirect$djk000$interceptRender(ItemEntityRenderer:526)
	at net.minecraft.client.render.entity.ItemEntityRenderer.render(ItemEntityRenderer:102)
	at net.minecraft.client.render.entity.ItemEntityRenderer.render(ItemEntityRenderer:18)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1482)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1230)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4966(class_1163.java:22)
	at net.linkle.valley.ValleyClient.lambda$onInitializeClient$2(ValleyClient.java:40)
	at io.github.coolmineman.bitsandchisels.BitItemModel.lambda$static$0(BitItemModel.java:60)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:49)
	at link.infra.indium.renderer.render.ItemRenderContext.renderQuad(ItemRenderContext.java:172)
	at link.infra.indium.renderer.render.ItemRenderContext.renderFallbackWithTransform(ItemRenderContext.java:246)
	at link.infra.indium.renderer.render.ItemRenderContext.fallbackConsumer(ItemRenderContext.java:228)
	at io.github.coolmineman.bitsandchisels.BitItemModel.emitItemQuads(BitItemModel.java:90)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:112)
	at net.minecraft.class_918.handler$eoc000$hook_method_23179(class_918.java:4057)
	at net.minecraft.class_918.method_23179(class_918.java)
	at com.unascribed.fabrication.logic.WoinaDrops.interceptRender(WoinaDrops.java:145)
	at net.minecraft.class_916.redirect$djk000$interceptRender(class_916.java:526)
	at net.minecraft.class_916.method_3996(class_916.java:102)
	at net.minecraft.class_916.method_3936(class_916.java:18)

-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 302805
	Entity Name:  Bit
	Entity's Exact location: 348.60, 83.00, 343.57
	Entity's Block location: World: (348,83,343), Section: (at 12,3,7 in 21,5,21; chunk contains blocks 336,0,336 to 351,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.12, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {Age:10s,Air:300s,FallDistance:0.0f,Fire:0s,Health:5s,Invulnerable:0b,Item:{Count:36b,id:"bitsandchisels:bit_item",tag:{bit:{Name:"valley:apple_leaves_empty",Properties:{distance:"3",persistent:"false"}}}},Motion:[0.0d,-0.12d,0.0d],OnGround:1b,PickupDelay:0s,PortalCooldown:0,Pos:[348.60111050109185d,83.0d,343.57027236043785d],Rotation:[-1.40625f,0.0f],UUID:[I;1125824670,1091519422,-1953309131,980029220],cardinal_components:{"bewitchment:additional_water_data":{Submerged:0b,WetTimer:0},"botania:iitem":{ApothecarySpawned:0b,_elvenPortal:0b,"botania:teleported":0b,manaInfusionCooldown:0,timeCounter:1370},"victus:flags":{Flags:0}},cpaCooldown:0,cpadidTP:0b,"fabrication:TrueAge":10L,"pehkui:scale_data_types":{"pehkui:base":{initial:0.22821775f,scale:0.22821775f,target:0.22821775f,ticks:2147483647}}}
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:521)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:169)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:160)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1482)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1230)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by CoolMineman** [comment]
![image](https://user-images.githubusercontent.com/62723322/169451762-9ee7aaac-ce3c-41f7-96c6-642fdec639e9.png)
broken mod report to their author if they care about 1.17.1
1.17.1 b&c is no longer receiving updates
