### ISSUE TITLE
Crashes on server with Fabric Loader 0.15.0+

### ISSUE THREAD

**Issue by Poopooracoocoo** [CoolMineman/BitsAndChisels#172]
Minecraft 1.20.1
Bits And Chisels 2.7.3
Fabric API 0.91.0
Fabric Loader 0.15.3

Crashes with:

java.lang.NoSuchFieldError: FORMAT

Works fine with Fabric Loader 0.14.25

This is caused by an older version of [Stacc](https://github.com/Devan-Kerman/Stacc/).

In the meantime, users can install Stacc API themselves and the newer version with the fix will be loaded instead.

## Log 

https://mclo.gs/5PKOfJl

<details>
<summary>Log </summary>

````

[20:11:07] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.3
[20:11:07] [main/INFO]: Loading 45 mods:
	- bitsandchisels 2.7.3
	   \-- stacc 1.5.2+boneless2ahhhh
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.1
[20:11:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[20:11:07] [main/INFO]: Compatibility level set to JAVA_16
[20:11:07] [main/INFO]: Compatibility level set to JAVA_17
[20:11:08] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[20:11:12] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: FORMAT
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.NoSuchFieldError: FORMAT
	at net.minecraft.item.ItemStack.<clinit>(ItemStack.java:133) ~[server-intermediary.jar:?]
	at net.minecraft.block.EntityShapeContext.<clinit>(EntityShapeContext.java:16) ~[server-intermediary.jar:?]
	at net.minecraft.block.ShapeContext.absent(ShapeContext.java:10) ~[server-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(class_4970.java:1028) ~[server-intermediary.jar:?]
	at net.minecraft.block.Block.isTransparent(Block.java:309) ~[server-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(class_4970.java:1281) ~[server-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(class_4970.java:843) ~[server-intermediary.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:1185) ~[server-intermediary.jar:?]
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	... 3 more


````

</details>

**Comment by eyskak** [comment]
id just like to add that this issue also occures on my 1.19.2 server and since so much of it is made with bits and chisles id really like it to get fixed soon :(((((

**Comment by Poopooracoocoo** [comment]
@eyskak Since Stacc API only fixed this in a version for 1.20.1, you'll have to just use Fabric Loader 0.14.25. You might like to ask the Stacc developer to backport it to 1.19.2.

**Comment by eyskak** [comment]
@Poopooracoocoo oh wait im so sorry ive completely misread this issue. Im having the same "java.lang.NoSuchFieldError: FORMAT" error but i dont have the mod "stacc api" and its caused by the bits and chisle mod (removing it stops my server crashing on startup). I left the log in the user support secion on your discord. Sorry for the confusion ive stayed up all night im so sleepy but like bits and chisle along with the create mod are basically the only two of 200 ish mods on my server that i actually care about

**Comment by Poopooracoocoo** [comment]
@eyskak Stacc API is included in Bits and Chisels...

>I left the log in the user support secion on your discord

I'm not sure if you were talking to me here but I'm just a user like you.

**Comment by eyskak** [comment]
@Poopooracoocoo oh im so sorry agian im so tired and stupid ive never used this website before and i misread the email i thought it said your name was CoolMineman. thanks for clearing things up though really appreciate it :)!

**Comment by WerySkok** [comment]
I had the same problem on 1.19.4, so I recompiled the mod for that version, maybe you can implement same fix for 1.20
https://github.com/WerySkok/BitsAndChisels/releases/tag/2.7.1

**Comment by SlayerTheChikken** [comment]
For those on 1.19.2, throw this in your mods folder 
https://github.com/TeamChikken/Stacc-CHKNFork-1.19.2/releases/tag/1.19.2

**Comment by TinsleyDevers** [comment]
Just saw the 1.19.2 workaround would love a fix for this on fabric 1.20.1 - v 0.15.x

**Comment by MasterKyle08** [comment]
Please do fabric 1.20.1 - 0.15.10

**Comment by Poopooracoocoo** [comment]
If you want to be subscribed to this issue, instead of leaving a comment just click the subscribe button. And instead of leaving a "+1" comment, consider using reactions! Comments can unnecessarily notify people. Thanks! A workaround that works on 1.20.1 has been added to the post itself by the way.

**Comment by itsdinkd** [comment]
> For those on 1.19.2, throw this in your mods folder https://github.com/TeamChikken/Stacc-CHKNFork-1.19.2/releases/tag/1.19.2

All your hotfixes.. you are epic man, thank you.

Crazy that none of the Devs of these mods implemented the fixes and are just saying screw everyone on these versions.
